"""Write build/network/SourceManifest.luau for fixtures/network.project.json.

The network diagnostic's Echo scripts put `input_sha256` into their evidence so a result can be tied
to the exact sources that produced it. The first pass generated this module on the owner's PC only,
so the place could not be built from a clone; this generator makes it reproducible.

  python3 tools/network_manifest.py            write it
  python3 tools/network_manifest.py --check    fail if it is missing or stale
"""
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "build" / "network" / "SourceManifest.luau"
INPUTS = [
    "fixtures/network.project.json",
    "fixtures/network/Echo.client.luau",
    "fixtures/network/Echo.server.luau",
    "fixtures/network/Settings.luau",
    "packages/Diagnostics/FaultQueue.luau",
]


def render():
    digest = hashlib.sha256()
    files = []
    for rel in INPUTS:
        data = (ROOT / rel).read_bytes().replace(b"\r\n", b"\n")
        digest.update(rel.encode() + b"\0" + data + b"\0")
        files += ["\t\t{", f'\t\t\tpath = "{rel}",', f'\t\t\tsha256 = "{hashlib.sha256(data).hexdigest()}",', "\t\t},"]
    return "\n".join(
        [
            "--!strict",
            "-- Generated by tools/network_manifest.py; do not edit.",
            "return table.freeze({",
            "\tschema = 1,",
            f'\tinput_sha256 = "{digest.hexdigest()}",',
            "\tfiles = {",
            *files,
            "\t},",
            "})",
            "",
        ]
    )


def main():
    text = render()
    if "--check" in sys.argv[1:]:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"stale or missing: {OUT.relative_to(ROOT)} (run python3 tools/network_manifest.py)")
            return 1
        print("network manifest up to date")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
